services:
  freqtrade-mcp:
    build: .
    container_name: freqtrade-mcp
    environment:
      - FREQTRADE_API_URL=${FREQTRADE_API_URL:-http://freqtrade:8080}
      - FREQTRADE_USERNAME=${FREQTRADE_USERNAME:-Freqtrader}
      - FREQTRADE_PASSWORD=${FREQTRADE_PASSWORD:-SuperSecret1!}
    restart: "no"
    env_file:
      - .env
    stdin_open: true
    tty: true
